### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Neon-kernel** [automatephp/automate#30]
Hi,

I would like to use Automate for my new workflow, but as far as i can see, last commit is from July 2019. Is the project still actively maintained? I cross my fingers because your tool seems to be really promising.

Thanks :)

**Comment by julienj** [comment]
Hi,
Yes of course, we use Automate every day for several projects!

**Comment by Neon-kernel** [comment]
Yeay cool 😁
I'll give it a try soon then!

**Comment by channaveer** [comment]
Hey hi I am stuck with the deployment of PHP Laravel project I am not sure how to make the following run

1. Copy **.env-example** to **.env** only once
2. Make **.env** a shared file 
3. Put the **storage** in a shared folder
4. Is there a way where I can run the Servers parallely

Currently, I am having the following script

```
repository: git@github.com:xxx/deployer-testing.git
platforms:
    production:
        default_branch: master
        max_releases: 5
        servers:
            Server-1:
                host: xx.xx.xx.xx
                user: root
                ssh_key: /Users/wifidabba/.ssh/id_rsa
                password: 12345
                path: /var/www/html

shared_files:
    - .env
shared_folders:
    - storage
pre_deploy:
    - "cp .env.example"
    - "php artisan key:generate"
on_deploy:
    - "composer install"
post_deploy:
    - "sudo service nginx restart"
    - "sudo service php7.4-fpm reload"
```

If you have any proper example of deploying Laravel to multiple server then really appriciated.
