### ISSUE TITLE
Yaml error

### ISSUE THREAD

**Issue by alexbogo** [automatephp/automate#32]
Hi,

First, thank you for the great tool. It works perfectly until I need the action for just one server. I am deploying symfony 4 webapp.
I am getting this error:

  **You cannot define a mapping item when in a sequence at line 2 (near "only: dev-one")**

Here is my yaml file:

```
repository: https://repository
platforms:
  dev:
    default_branch: master
    max_releases: 2
    servers:
      dev-one:
        host: dev.example.co.nz
        ssh_key:  /Users/user/.ssh/id_rsa
        user: user
        password: password
        path: /var/www/customers/customer
        port: 22
      dev-two:
        host: dev.example.co.nz
        ssh_key:  /Users/user/.ssh/id_rsa
        user: user
        password: password
        path: /var/www/customers/customer1
        port: 22
shared_files:

shared_folders:
  - Resources
  - public/nzqa
  - public/sdr
  - public/uploads
  - vendor
  - var
pre_deploy:
  - "sudo rm -Rf ../../shared/var/cache/prod"
  - "sudo rm -Rf ../../shared/var/cache/dev"
on_deploy:
  - "sudo chmod -Rf 777 ../../shared"
post_deploy:
  - "bin/console assets:install --symlink"
  only: dev-one
    - "php bin/console doctrine:cache:clear-result"

```
This is the same as in docs, I have tried making it a root node but then it doesn't run at all.
Can you please check?

Is it possible to have more than one "only: server" option? I have many customers, each with different DB connection string and env vars - but code is the same - all coming from one git repo, so I need to copy .env file for each customer to their root web dir. Or do you have better option how to approach this? 

Thanks in advanced. 
Stay safe.

**Comment by julienj** [comment]
Hi,

With version 3, you must now use the following syntax

```
post_deploy:
  - cmd: "bin/console assets:install --symlink"
    only: dev-one
  - "php bin/console doctrine:cache:clear-result"
```
Thanks for report, i will modify the documentation.

For the problem with .env:
A solution is add in your configuration :
```
shared_files:
- .env.local
```
On each server you can add the DB connection string in .env.local
