### ISSUE TITLE
cache_tool plugin can't find phar

### ISSUE THREAD

**Issue by foxycode** [automatephp/automate#35]
When added cachetools config section:
```yaml
plugins:
  cache_tool:
    version: 5.0.0
    opcache: true
```

I get following error:
```bash
php cachetool.phar opcache:reset --fcgi

 [ERROR] Could not open input file: cachetool.phar
```

Looks like I need to download cachetool manually, but in that case, what is `version` config option good for? Wouldn't be better to add `path` option? Does Automate look for `cachetool` executable in `$PATH`?

Also, what if my PHP isn't fcgi? This should be configurable too.
